# Generated by Django 5.2 on 2025-05-10 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_testimonial_alter_emp_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
